services:
  - type: worker
    env: node
    name: phantombuster-to-supabase
    buildCommand: "npm install && npm run build"
    startCommand: "node dist/index.js"
    autoDeploy: true
    plan: starter
    envVars:
      - key: TRIGGER_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false